### ISSUE TITLE
Update "More Projects" section

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/1Hive#10]
Currently there's just a button. It would be great if there was a picture and/or it showcased some of the past and current 1Hive projects.

**Comment by burrrata** [comment]
Status: waiting for merge of index.js refactor, then will update this section

**Comment by yeqbfgxjiq** [comment]
Thinking a picture of a garden would be good. Then it's like every app/thing we ship plants one more thing in the garden, and then bees hangout in the garden pollinating plants and updating the repos, making honey, etc... It fits with the theme lol 

Submitted a PR with the change
- https://github.com/1Hive/website/pull/31

In the future it would be great to actually display all the different apps and have a brief little summary of them here, but for now I think this is fine. If the PR gets merged I'll close this Issue :)

**Comment by burrrata** [comment]
In the future it would be great to actually display all the different apps and have a brief little summary of them here, but for now I think this is fine. If the PR gets merged I'll close this Issue :)

**Comment by yeqbfgxjiq** [comment]
This got taken care of. Thanks @lkngtn
