### ISSUE TITLE
Pushing changes to GitHub Pages branch removes custom domain setting

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/1Hive#18]
As advertised: pushing changes to GitHub Pages branch removes custom domain setting. This could be a problem with another repo sharing the same CNAME / custom domain.
- https://github.com/travis-ci/travis-ci/issues/7538

> If you own the other GitHub Pages repository that is using your custom domain in its CNAME file, then you must remove the custom domain from your other repository's CNAME file before you can use it in a different pages site repository.
- https://help.github.com/en/articles/troubleshooting-custom-domains#github-repository-setup-errors

It could also be that the CNAME records set at the DNS provider are not pointing to the right place.
> If you configured ALIAS, ANAME, or CNAME records through your DNS provider, then your DNS record should point to your GitHub Pages default domain, such as YOUR-GITHUB-USERNAME.github.io. Your default GitHub Pages domain is determined by the type of pages site you have.
- https://help.github.com/en/articles/troubleshooting-custom-domains#dns-configuration-errors

Atm I'm really not sure which it is, although I'm leaning towards the multiple repo CNAME issue...

BTW: as far as GitHub Pages is concerned, setting a custom domain in the settings of a repo is the same as setting a CNAME in the root directory of the project. 

<br>

We can still publish to 1hive.org, but we just need to go into the website repo settings and set 1hive.org as the custom domain every time we push to the gh-pages branch. It would be great if GitHub remembered that we want the Custom Domain to be 1hive.org.

**Comment by lkngtn** [comment]
as far as I can tell there are no other repos that are using the CNAME 1hive.org... but there is a CNAME in both the master branch and the gh-pages branch. I'm not sure why that would make a difference though as gh-pages is configured to serve the gh-pages branch only. 

I feel like maybe there is something going on in the docusaurus publish script... though I know we didnt seem to have that problem before with the mvp repo.

**Comment by lkngtn** [comment]
https://stackoverflow.com/questions/55322143/custom-domain-is-reset-after-gh-pages-deployment

(unfortunately no resolution).

**Comment by yeqbfgxjiq** [comment]
I tried publishing with and without the CNAME file, but it didn't make a difference. Also, whenever you're on the master branch and run the deploy script (`GIT_USER=your-username CURRENT_BRANCH=master yarn run publish-gh-pages`) it pushes the branch you're on (usually master) to the gh-pages branch (where GitHub pages looks for stuff to publish because that's how it is in the settings).

Also checked the `siteConfig.js` and everything looks fine. Oddly enough though, with MVP I had to switch between the different [commented/uncommented params](https://github.com/1Hive/mvp/blob/master/website/siteConfig.js#L28) in `siteConfig.js`, but on the newer version I can build/run it locally and publish it with the params configured for publishing to the website. Not sure why this is...

**Comment by yeqbfgxjiq** [comment]
As annoying as it is, this bug is not critical for the MVP so I say let's just acquire some technical debt and leave it for down the road.

**Comment by lkngtn** [comment]
I think this is solved with https://github.com/1Hive/website/blob/bf0ecd83d7395a0b3d356def1f84027a03378267/website/siteConfig.js#L39

Solution was found here: 
https://stackoverflow.com/questions/53080767/docusaurus-cname-file-is-deleted-after-each-build

**Comment by yeqbfgxjiq** [comment]
Nice! :)
