### ISSUE TITLE
Guide: How to add Honey on metamask

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/1Hive#19]

**Comment by lkngtn** [comment]
I think we should make the guide generic (how to add Aragon organization tokens to metamask), and then we can reference it in the onboarding guide saying something like "we recommend adding `Honey` to your wallet interface, if you are using metamask here is a guide."

**Comment by yeqbfgxjiq** [comment]
Created an "adding tokens to Metamask" section in the Guide For 1Hive BEEs PR
- https://github.com/1Hive/website/pull/26

Do you guys feel like the guide needs pictures too or are we happy with it and ready to close this PR?
- personally I thought the process was so easy it was surprising, but I don't know if the walk through I created communicates that effectively

**Comment by yeqbfgxjiq** [comment]
No response so I'll assume that the current guide is good enough. If not though, please open this issue back up to discuss :)
