### ISSUE TITLE
Guides for 1Hive BEE actions

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/1Hive#20]
We need to document how to do things in the 1Hive DAO
- request to become a curator, reviewer, or worker
- vote
- other stuff I'm not thinking of atm

**Comment by yeqbfgxjiq** [comment]
Starting to put together a draft on this in the guide-for-1hive-bees branch
- https://github.com/1Hive/website/tree/guide-for-1hive-bees

**Comment by burrrata** [comment]
Once the Projects App is back online, we'll need to create a guide for that too

**Comment by yeqbfgxjiq** [comment]
Done
- https://1hive.org/docs/wiki/guides/1Hive.html
