### ISSUE TITLE
Create a page that shows the current reviewers, curators, and workers

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/1Hive#21]
It would be helpful to create a page with the current Reviewers/Curators/Workers that shows who's in each role as well as their "areas of expertise".

Thinking this way if you have a question about X it's easier to find someone that can help or know who to reach out to. Probably not much of an issue in the beginning being how everyone's weighing in on almost everything, but as we grow it could help the community network and collaborate more effectively.

We should also add to each section (reviewer, curator, worker) the specific permissions associated with those roles.

This page could go in the website's Contributing section, right after the "Naviagting Our GitHub" page
- https://1hive.org/docs/contribute/github.html

**Comment by yeqbfgxjiq** [comment]
While we could make this yet another page in the docs, I think that pushing this on the homepage of the website makes the most sense. DAOs are all about community, and showcasing core members of the community helps people feel like their contributions are valued. It also allows new members/readers to know who to reach out to for help/feedback/advice on specific things.

<s>Furthermore, Docusaurus has a built in feature to make this possible in `siteConfig.js` where you can add "users" by creating a JS object with a title, picture, and link to specific data. This would allow people to see in a glance who's who in the DAO, and then click to see their profiles (hopefully soon the [profiles concept that @stellarmagnet is working on](https://forum.aragon.org/t/profiles-in-aragon/912)).</s>
Does not work on the fbflipper fork. Exploring other options, but atm it's not critical to ship the MVP. Ignore this comment and just proceed with a Markdown file in the Contributing section.

**Comment by yeqbfgxjiq** [comment]
Just created a PR for this [here](https://github.com/1Hive/website/pull/25)

**Comment by lkngtn** [comment]
One thing we should consider, is if/where we should maintain a mapping between user names and addresses. 

I'm about to create votes to mint honey for all the current `Bee` and ideally  everyone would have custom labels configured so that they could see who is what address.

**Comment by yeqbfgxjiq** [comment]
Yeah I've been thinking about this a lot too. It's frustrating that it's such a manual process to link onchain data with offchain data. Hopefully the [Aragon Profiles](https://forum.aragon.org/t/profiles-in-aragon/912) thing that @stellarmagnet is working on will help and maybe we could just use that?

**Comment by yeqbfgxjiq** [comment]
Done. While this is not perfect, it's more than enough for now. Eventually an automagic script to pull data from the DAO and update the website would be great, but that's a ways out. 
- https://1hive.org/docs/contribute/roles-responsibilities.html
