### ISSUE TITLE
Simplifying the Navigating our Github page

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/1Hive#23]
On the [Navigating Our GitHub](https://1hive.org/docs/contribute/github.html) page on the website, there's a section called [Important Repos](https://1hive.org/docs/contribute/github.html#important-repos). Rather than keeping that page updated as the DAO changes, what if we just pointed people to the Projects app on the DAO where they can see relevant repos that have been added and a curated list of the top issues that need to be worked on? Seems a lot easier for the reader and the 1Hive team than trying to keep a website up to date with multiple repos/issues from all over GitHub

**Comment by lkngtn** [comment]
I was actually not really thinking that projects in "important repos" I was thinking more like things like Ideas (which have a special purpose and not really related to a specific repo, or the dao repo, which is where issues should be filed related to the dao configuration.

I don't think those repos will change nearly as frequently as the active projects might.

**Comment by yeqbfgxjiq** [comment]
Got it. I still think it makes sense to move people towards the DAO though because all important repos will be added to the Projects app, and there they can see a curated list of what's being worked on, and if someone wants to learn more they can always go to the GitHub repo from the links in the DAO. Overall I fell like this would reduce the amount of work we have to do when things change and would also provide a better (and more unique) onboarding experience for the user rather than having them browse GitHub. The DAO is the heart of the org and what makes 1Hive unique, so I think it makes sense to get people there as fast as possible.

**Comment by lkngtn** [comment]
I generally agree with the sentiment, but I'm also wary of how many clicks and hoops a new person would have to get through to get to something like the "Ideas" repo. Ideas may be a special case though as Ideas probably won't ever have funded tasks, so it doesn't really belong in the projects app anyways. 

If you direct them to the projects app, they will see a list of repos without much context, and clicking through them will take them to the list of tasks, when they really should start at the projects readme/contributor guide. 

While I agree that the DAO is at the heart of things, and also unique. I think its important to think about what the most efficient flow is for a user to actually get involved in the project, and throwing them right into the DAO may not be the most effective...

**Comment by yeqbfgxjiq** [comment]
> If you direct them to the projects app, they will see a list of repos without much context, and clicking through them will take them to the list of tasks, when they really should start at the projects readme/contributor guide.

This is a good point. I was thinking about this and wasn't sure if the Projects app only shows the repo name, or if there's a way to click on it to see a brief description of the repo too. Since I'm locked out of the Projects app I couldn't check. It would be ideal if we could add context within the Projects app. If not, then I think it makes sense to list and link to the main repos **and** the Projects app so people see both and can go to repos to get info and also know the Projects app has a curated list of top priorities. 

> its important to think about what the most efficient flow is for a user to actually get involved in the project

100%. Ideally this could all be integrated in a seamless way, but as is there's a bit of friction because DAO and on-chain things are generally separate from other things. Do you know if Autark is open to feedback to improve the UX/UI around the apps, or are they pretty much shipping as is and then moving on to other things?

**Comment by lkngtn** [comment]
> 100%. Ideally this could all be integrated in a seamless way, but as is there's a bit of friction because DAO and on-chain things are generally separate from other things. Do you know if Autark is open to feedback to improve the UX/UI around the apps, or are they pretty much shipping as is and then moving on to other things?

I'm sure they would appreciate feedback to improve UX/UI, more feedback is generally always better, but there is no guarantee they will be able to address everything. I'm sure they would also welcome PRs, so if we have specific issues we can potentially contribute back.

**Comment by yeqbfgxjiq** [comment]
Cool. Well I'll drop them a line when the app is back up, but as is I can't really look at it to give concrete suggestions. 

> I'm sure they would also welcome PRs, so if we have specific issues we can potentially contribute back.

Since Autark is a flock team with funding and 1Hive is a volunteer org without funding I think it makes more sense for them to purchase HONEY and stake it to a task for that feature rather than having us do it out of altruism. Altruism is **awesome**, but we're here to make open source sustainable and that requires dogfooding the 1Hive model (as described in the handbook) so that we can test it first and make sure it actually works before recommending anyone else try it out. Our #1 goal is to figure out how to make open source community driven development sustainable. 1Hive is the project/test for that, so we need to build and use our own model before doing anything else.

**Comment by lkngtn** [comment]
> Since Autark is a flock team with funding and 1Hive is a volunteer org without funding I think it makes more sense for them to purchase HONEY and stake it to a task for that feature rather than having us do it out of altruism. Altruism is awesome, but we're here to make open source sustainable and that requires dogfooding the 1Hive model (as described in the handbook) so that we can test it first and make sure it actually works before recommending anyone else try it out. Our #1 goal is to figure out how to make open source community driven development sustainable. 1Hive is the project/test for that, so we need to build and use our own model before doing anything else. 

🤷‍♂️ 

Personally don't think we should go so far as to only contribute if we are getting paid. It's not really in the spirt of open source. We are using autarks apps for free, and aragon apps for free, and when we see gaps that impact us (and our goals), its far more productive to adopt an attitude of collaboration rather than expecting them to provide software as anything other than as is and without warranty. By contributing when we see an opportunity we build a good reputation in the community, while helping solve a problem that we are currently experiencing, and solving a problem that people that are adopting our model will experience. 

> Our #1 goal is to figure out how to make open source community driven development sustainable. 1Hive is the project/test for that, so we need to build and use our own model before doing anything else.

Obviously we want to prioritize our efforts as we have limited bandwidth and want to have the biggest possible impact with our time... but currently the Autark applications are a core part of the model that we trying to operationalize and spread. We are on the same team, and we should act like it.

**Comment by yeqbfgxjiq** [comment]
> Personally don't think we should go so far as to only contribute if we are getting paid.

Agreed. We're obviously not doing that, and I don't want to move towards that kind of a mindset or model. What I'm trying to say is that we shouldn't have the attitude that we're just going to work work work without asking for anything in return. There should always be an equal exchange of energy. Money (and now tokens) is how humans exchange value. We should make it clear that we're happy to contribute and provide value, but that it would be awesome if 3rd parties that benefit from our work contributed by acquiring HONEY to support and hive and signal things they think are important. How to communicate that in a clear way without sounding too needy/transactional is going to be a challenge, but it's essential if we're going to scale sustainably.  

> We are on the same team, and we should act like it.

100%. The work we're doing contributes to many projects in the Aragon ecosystem (current and future). We're helping to test out new apps and showcase and (to some extent) document them. We're also building new apps that other projects can use. We're also engaging with the broader Aragon community on many important topics. It's all positive sum. I'm saying that culturally we should set the expectation that when we contribute value, value also flows back. This is essential to making the whole thing sustainable. We need to change the mindset in open source from seeing altruism as a way to virtue signal and/or looking down on money/tokens/economics. We need to acknowledge the constraints of the real world and use tokens/money to say thank you and support community contributions. All of this is possible because Ethereum token holders supported Aragon, and Aragon supported Autark. That chain of support needs to flow through to 1Hive

**Comment by yeqbfgxjiq** [comment]
This thread kind of got off topic. Sorry about that. 


Anyways, I'm happy with the current [Navigating Our GitHub](https://1hive.org/docs/contribute/github.html) page and agree with your [first comment](https://github.com/1Hive/website/issues/23#issuecomment-491611688) in this thread.

@lkngtn closing this Issue, but please open it back up if you feel like it requires more work :)
